name: Generate Pac-Man Game

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate SVG
        uses: abozoana/pacman-contribution-graph@v1.0.14
        with:
          user: ashwinthomasmathew
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: output
          build_dir: dist
          committer: "Ashwin Thomas Mathew <ashwinthomasmathew99@gmail.com>"
          author: "Ashwin Thomas Mathew <ashwinthomasmathew99@gmail.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
